import type { LandingContent } from '@/components/InventoryLanding';
export const suvLanding: LandingContent = {
  eyebrow: 'SPACE FOR YOUR NEXT CHAPTER', heading: 'Used SUVs', accent: 'in PEI.',
  intro: 'Compare current used SUVs across makes, prices and kilometres, then choose the space and capability you actually need.', body: 'SUV',
  sections: [
    { heading: 'Choose the right size of SUV', paragraphs: ['Compact SUVs are often easier to park and can be a practical fit for a daily commute. Larger models may give passengers and cargo more room, but compare fuel, tire and insurance costs as well as the asking price.', 'Bring your child seat, stroller or sports gear when you view a vehicle. Photos rarely show how much usable space remains with everyone aboard.'] },
    { heading: 'Compare the features that matter on PEI', paragraphs: ['Check the drivetrain, tires, service history and visibility before choosing by model name alone. AWD can help with traction in some conditions, while suitable tires and careful driving remain essential for winter roads.'], bullets: ['Filter by price and kilometres to find a realistic shortlist.', 'Check cargo access, rear-seat room and the condition of the tires.', 'Ask about warranty terms, inspection and any reconditioning completed.'] },
    { heading: 'What if the right SUV is not here today?', paragraphs: ['The inventory feed changes as vehicles arrive and sell. If the current list does not fit, use Car Finder to tell us your preferred size, budget, features and timeline.'] },
  ],
  guideLinks: [{ label: 'How to choose a used SUV', href: '/guides/used-suv-buying-guide-pei' }, { label: 'Compare current Tiguans', href: '/used-volkswagen-tiguan-pei' }, { label: 'Compare Atlas-family SUVs', href: '/used-volkswagen-atlas-pei' }, { label: 'Sedan or compact SUV for PEI?', href: '/guides/used-sedan-vs-compact-suv-pei' }, { label: 'Browse every used vehicle', href: '/used' }],
};
export const awdLanding: LandingContent = {
  eyebrow: 'TRACTION FOR ISLAND ROUTES', heading: 'Used AWD & 4WD', accent: 'in PEI.',
  intro: 'Explore currently listed all-wheel-drive and four-wheel-drive vehicles and compare them on price, mileage and everyday fit.', drive: 'awd',
  sections: [
    { heading: 'Start with the roads you drive', paragraphs: ['An AWD or 4WD vehicle may be useful for an unplowed driveway, rural route or regular travel before roads are cleared. The best fit still depends on the specific vehicle, tires, driver and conditions. AWD helps a vehicle get moving in slippery conditions; it does not guarantee shorter braking distance.'] },
    { heading: 'Check the total ownership cost', paragraphs: ['Compare fuel use, tire replacement costs, insurance and maintenance alongside the price. A front-wheel-drive alternative with suitable tires may also be worth considering if your driving is mostly on maintained roads.'], bullets: ['Ask about tire age, tread and whether the set matches the vehicle requirements.', 'Review service history for the specific drivetrain system.', 'Test drive the vehicle on the kinds of roads you use regularly.'] },
    { heading: 'Keep your shortlist flexible', paragraphs: ['Our current AWD and 4WD selection depends on the live inventory feed. If the options below do not fit your budget or body-style needs, share those details through Car Finder and we can follow up when a closer match is available.'] },
  ],
  guideLinks: [{ label: 'AWD versus FWD on PEI', href: '/guides/awd-vs-fwd-pei' }, { label: 'PEI winter tire decisions', href: '/guides/winter-tires-pei-used-car' }, { label: 'Shop used trucks', href: '/used-trucks-pei' }, { label: 'Shop used SUVs', href: '/used-suvs-pei' }],
};
export const charlottetownLanding: LandingContent = {
  eyebrow: 'SHOP LOCAL, DRIVE ISLAND-WIDE', heading: 'Used cars near', accent: 'Charlottetown.',
  intro: 'Browse current used cars, SUVs and trucks serving Charlottetown and drivers across Prince Edward Island.',
  sections: [
    { heading: 'A local starting point for your search', paragraphs: ['Shopping near Charlottetown lets you compare several kinds of used vehicles in one place. Start with body style, budget and mileage, then inspect the details of a few specific vehicles instead of trying to choose from every listing at once.', 'The vehicles shown above come from our current feed. Availability can change, so ask us to confirm a vehicle before making a trip.'] },
    { heading: 'Compare beyond the sticker price', paragraphs: ['A good shortlist accounts for condition, maintenance, tires, insurance and the total cost of financing. Test drive the routes you use regularly, and ask about history, inspection and any included coverage.'], bullets: ['Use the filters for make, body style, price, kilometres and drivetrain.', 'Open a vehicle page to review its VIN, features and photos.', 'Send a question on the vehicle page when you are ready for more detail.'] },
    { heading: 'Looking from elsewhere on the Island?', paragraphs: ['You can research inventory online from Summerside, Stratford, Cornwall and other PEI communities. Share the vehicles you like and arrange the next step with our team. If no listing fits, use Car Finder and describe what you need.'] },
  ],
  guideLinks: [{ label: 'PEI used-car checklist', href: '/guides/buying-a-used-car-in-pei' }, { label: 'Shop from Summerside', href: '/used-cars-summerside-pei' }, { label: 'Compare used SUVs', href: '/used-suvs-pei' }, { label: 'Explore financing', href: '/finance' }],
};
export const makeLandings: Record<string, LandingContent> = {
  volkswagen: { eyebrow: 'CURRENT VOLKSWAGEN SELECTION', heading: 'Used Volkswagen vehicles', accent: 'in PEI.', intro: 'Explore current used Volkswagen cars and SUVs in PEI, with live prices, kilometres and VIN-specific details.', make: 'Volkswagen', sections: [
    { heading: 'Compare the size that fits your routine', paragraphs: ['A Taos, Tiguan and Atlas can offer very different passenger and cargo space. A Jetta or Golf may be a better fit if you prioritize a smaller footprint. Check the active vehicles above rather than assuming every model or trim is available today.'] },
    { heading: 'Check the exact vehicle and its records', paragraphs: ['Confirm the trim, equipment, tires, service history and inspection status for the VIN you are considering. If AWD is important, verify the drivetrain on that specific listing and ask how it has been maintained. An independent pre-purchase inspection can help you assess condition beyond the information in an online listing.'], bullets: ['Compare asking price with year, kilometres and condition.', 'Bring your passengers or gear to a viewing to check the real fit.', 'Review written financing terms and the full cost of ownership.'] },
    { heading: 'Keep your options open', paragraphs: ['Used inventory moves quickly. If the model, price range or features you want are not currently listed, tell us what to watch for and we can follow up when a potential match appears.'] },
  ], guideLinks: [{ label: 'Compare current Tiguans', href: '/used-volkswagen-tiguan-pei' }, { label: 'Compare Atlas-family SUVs', href: '/used-volkswagen-atlas-pei' }, { label: 'Used Volkswagen checklist', href: '/guides/used-volkswagen-checklist-pei' }, { label: 'Compare AWD and FWD', href: '/guides/awd-vs-fwd-pei' }, { label: 'Browse all used vehicles', href: '/used' }] },
  honda: { eyebrow: 'CURRENT HONDA SELECTION', heading: 'Used Honda vehicles', accent: 'in PEI.', intro: 'Explore current used Honda cars and SUVs, with live pricing and vehicle details.', make: 'Honda', sections: [
    { heading: 'Compare the Honda that fits your day', paragraphs: ['A Honda badge can cover very different vehicles. Compare the specific model’s passenger room, cargo space, fuel needs and features against your daily route. A compact car and an SUV can solve different problems even when the price is similar.'] },
    { heading: 'Review each vehicle on its own merits', paragraphs: ['Price, kilometres, condition and service history matter more than a general reputation. Open each listing for the VIN and equipment, then ask about inspection, past claims and available maintenance records.'], bullets: ['Check tires and brakes against your expected driving.', 'Try the cabin and cargo area in person.', 'Compare the full purchase and financing cost, not only the payment.'] },
    { heading: 'If the model you want is missing', paragraphs: ['The live selection can change quickly. Tell us the Honda model, year range, budget and features you are looking for through Car Finder.'] },
  ], guideLinks: [{ label: 'Used-car buying checklist', href: '/guides/buying-a-used-car-in-pei' }, { label: 'Buying a used hybrid in PEI', href: '/guides/buying-a-used-hybrid-in-pei' }, { label: 'Browse all used vehicles', href: '/used' }] },
  kia: { eyebrow: 'CURRENT KIA SELECTION', heading: 'Used Kia vehicles', accent: 'in PEI.', intro: 'Compare current used Kia vehicles in PEI, including price, kilometres, body style and available equipment.', make: 'Kia', sections: [
    { heading: 'Match the model to your routine', paragraphs: ['Kia cars and SUVs span different sizes and purposes. Think about passengers, parking, cargo and winter routes before narrowing the list. Check the actual trim and equipment on each vehicle rather than assuming features from the model name.'] },
    { heading: 'Questions worth asking', paragraphs: ['For each listing, review the VIN, service history, tire condition and included coverage. Warranty transfer rules can depend on the vehicle and program, so request the exact terms in writing if warranty is important to your decision.'], bullets: ['Compare the price with kilometres and condition.', 'Test visibility, seating and cargo access.', 'Review financing terms and total ownership costs.'] },
    { heading: 'Keep the search open', paragraphs: ['If the Kia you want is not in the live inventory, tell us your preferred model, budget and timeline in Car Finder.'] },
  ], guideLinks: [{ label: 'Used SUV buying guide', href: '/guides/used-suv-buying-guide-pei' }, { label: 'Browse all used vehicles', href: '/used' }] },
  nissan: { eyebrow: 'CURRENT NISSAN SELECTION', heading: 'Used Nissan vehicles', accent: 'in PEI.', intro: 'Browse current used Nissan vehicles and compare the details that shape ownership.', make: 'Nissan', sections: [
    { heading: 'Start with the model and how you drive', paragraphs: ['Choose the body style that suits your passengers, cargo and regular routes. Then compare trims and actual equipment. A vehicle’s condition and maintenance history should carry weight alongside its year and kilometres.'] },
    { heading: 'Inspect and compare thoughtfully', paragraphs: ['Ask for service records, inspection information and vehicle history when available. On a test drive, check how the vehicle shifts, brakes, steers and handles everyday road speeds. A qualified independent inspection can be useful before buying a higher-kilometre vehicle.'], bullets: ['Compare price and mileage with similar vehicles.', 'Check tire type and condition for your routes.', 'Review all written sale and financing terms.'] },
    { heading: 'Need a different Nissan?', paragraphs: ['The listings above reflect current availability. Use Car Finder with your model, budget and feature preferences if nothing matches today.'] },
  ], guideLinks: [{ label: 'PEI used-car checklist', href: '/guides/buying-a-used-car-in-pei' }, { label: 'Browse all used vehicles', href: '/used' }] },
};

export const truckLanding: LandingContent = {
  eyebrow: 'CURRENT PICKUP SELECTION', heading: 'Used trucks', accent: 'in PEI.',
  intro: 'Compare the pickups currently in the DrivePEI feed, from daily-use trucks to larger work and recreation options. Every result below is a live truck listing.', body: 'Truck',
  sections: [
    { heading: 'Start with the job the truck must do', paragraphs: ['Write down what you will actually carry, tow and park. A pickup that suits a weekly highway commute may differ from one chosen for a boat, trailer or jobsite. Compare cab access, bed length, payload and towing limits for the exact year, trim and equipment; a model badge alone does not establish a safe rating.', 'If towing matters, ask for the owner manual and the vehicle-specific equipment details, then account for passengers, cargo and trailer tongue weight. Do not rely on a generic maximum from an advertisement.'] },
    { heading: 'Price the complete truck', paragraphs: ['Look at the VIN, kilometres, tires, underbody, service records and any inspection or reconditioning information. Four-wheel drive and larger tires can affect maintenance and replacement costs. Check whether a hitch, bed cover or second tire set is actually included with the vehicle you are considering.'], bullets: ['Measure parking fit and rear-seat access before you travel.', 'Ask about past commercial or towing use and review the available history.', 'Use a test drive and independent inspection to assess condition.'] },
    { heading: 'When no pickup fits today', paragraphs: ['Truck stock can change quickly. Send your preferred cab, budget, drivetrain and towing or payload requirements through Car Finder, and we can watch for a suitable arrival.'] },
  ],
  guideLinks: [{ label: 'PEI winter tire decisions', href: '/guides/winter-tires-pei-used-car' }, { label: 'MVI versus independent inspection', href: '/guides/pei-mvi-vs-prepurchase-inspection' }, { label: 'Compare AWD and 4WD vehicles', href: '/used-awd-pei' }, { label: 'Browse all used vehicles', href: '/used' }],
};

export const tiguanLanding: LandingContent = {
  eyebrow: 'CURRENT TIGUAN SELECTION', heading: 'Used Volkswagen Tiguan', accent: 'in PEI.',
  intro: 'Compare the Tiguans currently listed in PEI by year, trim, kilometres and price. The results stay limited to the Tiguan model as inventory changes.', make: 'Volkswagen', models: ['Tiguan'],
  sections: [
    { heading: 'Compare the exact year and trim', paragraphs: ['The current Tiguan selection spans more than one model year and trim. Open two VIN pages side by side and confirm the equipment that matters to you: seating, cargo access, driver assistance and the tires included. A familiar trim name does not prove every used vehicle has the same options or condition.', 'If you need all-wheel drive, check the drivetrain shown on the specific listing and verify it with the vehicle. Compare its service history and tires as well as the badge.'] },
    { heading: 'Test the family and commute fit', paragraphs: ['Bring a child seat, stroller, dog crate or work gear to see whether the actual vehicle works for your routine. Try the rear doors and cargo opening, then drive a safe route that includes the town and highway speeds you use. Ask for the current MVI information, service records and any available history report.'], bullets: ['Compare price against year, kilometres, trim and condition.', 'Check tire type, size, wear and what comes with the sale.', 'Review written financing terms and the total purchase cost.'] },
    { heading: 'Watch for a specific Tiguan', paragraphs: ['If your preferred year, budget or equipment is missing, use Car Finder with those details. Current listings may sell before an appointment, so ask us to confirm the VIN before making a trip.'] },
  ],
  guideLinks: [{ label: 'Used Volkswagen checklist', href: '/guides/used-volkswagen-checklist-pei' }, { label: 'Compare AWD and FWD', href: '/guides/awd-vs-fwd-pei' }, { label: 'PEI winter tire decisions', href: '/guides/winter-tires-pei-used-car' }, { label: 'Compare Atlas-family SUVs', href: '/used-volkswagen-atlas-pei' }],
};

export const atlasLanding: LandingContent = {
  eyebrow: 'CURRENT ATLAS FAMILY', heading: 'Used Volkswagen Atlas', accent: 'in PEI.',
  intro: 'See current Atlas and Atlas Cross Sport listings together, then compare each model and VIN for seating, cargo room, equipment and price.', make: 'Volkswagen', models: ['Atlas', 'Atlas Cross Sport'],
  sections: [
    { heading: 'Atlas or Atlas Cross Sport?', paragraphs: ['These are distinct model names in the inventory feed, so check which one each listing shows before comparing. Bring your passengers and regular cargo to a viewing; seating layout, usable space and access may vary by model year and vehicle. Compare the actual vehicle rather than treating the two names as interchangeable.'] },
    { heading: 'Look past the size', paragraphs: ['For each VIN, confirm drivetrain, trim, tires, service history and inspection status. Larger wheels or a different tire size can change your replacement budget. If you use the vehicle for long Island trips, test highway comfort, visibility and the cargo arrangement with the seats set for your family.'], bullets: ['Check how child seats or adult passengers fit.', 'Measure the items that must fit through the cargo opening.', 'Compare year, kilometres and condition before judging the price.'] },
    { heading: 'Set up a targeted search', paragraphs: ['Atlas-family availability changes with the daily feed. If the right layout or price is absent, tell us which model, seating arrangement and budget you need through Car Finder. Ask us to confirm the exact vehicle before travelling.'] },
  ],
  guideLinks: [{ label: 'Used Volkswagen checklist', href: '/guides/used-volkswagen-checklist-pei' }, { label: 'Used SUV buying guide', href: '/guides/used-suv-buying-guide-pei' }, { label: 'Compare current Tiguans', href: '/used-volkswagen-tiguan-pei' }, { label: 'Browse all used SUVs', href: '/used-suvs-pei' }],
};

export const summersideLanding: LandingContent = {
  eyebrow: 'SHOP FROM SUMMERSIDE', heading: 'Used cars for', accent: 'Summerside drivers.',
  intro: 'Browse current PEI used inventory online from Summerside, then confirm the exact vehicle and viewing location before planning a visit.',
  sections: [
    { heading: 'Make the trip worthwhile', paragraphs: ['Start with a short list of VINs, prices and must-have features. Ask whether each vehicle is still available, where it can be viewed and when an appointment is possible before driving from Summerside. DrivePEI is an online used-vehicle site and does not have a separate Summerside storefront.', 'If a vehicle is no longer available, send your preferred size, budget and features through Car Finder. A focused request is easier to act on than a long list of loosely related vehicles.'] },
    { heading: 'Compare an Island-ready vehicle', paragraphs: ['For a commute around Summerside or travel across PEI, check tires, visibility, fuel use, insurance and service history alongside the asking price. Open each vehicle page for its VIN and listed details, then ask about the current inspection and an independent pre-purchase assessment if you want one.'], bullets: ['Confirm price, availability and viewing location before travelling.', 'Bring the people or gear you need the vehicle to carry.', 'Review the written total cost and financing terms before deciding.'] },
    { heading: 'Plan the ownership paperwork', paragraphs: ['PEI lists a signed vehicle permit, bill of sale, motor vehicle inspection form and valid insurance card for an ownership transfer. Ask which steps the seller will handle and verify current requirements with Access PEI. Our registration guide walks through the questions before you collect the keys.'] },
  ],
  guideLinks: [{ label: 'PEI registration after a used-car purchase', href: '/guides/pei-used-car-registration-transfer' }, { label: 'PEI winter tire decisions', href: '/guides/winter-tires-pei-used-car' }, { label: 'Dealer versus private sale', href: '/guides/dealer-vs-kijiji-used-car-pei' }, { label: 'Browse trucks', href: '/used-trucks-pei' }],
};
